#普通数据的配置
name: zhangsan

#对象的配置
person:
  name: zhangsan
  age: 18
  addr: beijing

#行内对象配置
#person: {name: zhangsan,age: 18,addr: beijing}

#配置数组或集合(普通字符串)
city:
  - beijing
  - tainjing
  - chongqi
  - shanghai

#city: [beijing,tianjing,chongqi,shanghai]

#配置数组或集合(对象)
student:
 - name: tom
   age: 18
   addr: beijing
 - name: lucy
   age: 17
   addr: tianjing

#student: [{name: tom,age: 18, addr: beijing},{name: lucy,age: 17, addr: tianjing}]

#map配置
map:
  key1: value1
  key2: value2

server:
  port: 8099


